"""
ORACLE of Lyngby — Advisor Database (enriched)
================================================
Auto-generated by generate_summaries.py.
Contains all original fields plus ``supervisor_summary``.
Do not edit manually — re-run generate_summaries.py to regenerate.
"""

ADVISORS = [{'name': 'Per Bækgaard',
  'initials': 'pgba',
  'title': 'Associate Professor',
  'section': 'Cognitive Systems',
  'email': 'pgba@dtu.dk',
  'profile_url': 'https://people.compute.dtu.dk/pgba/',
  'orbit_url': 'https://orbit.dtu.dk/en/persons/per-b%C3%A6kgaard',
  'research_interests': ['Human-Computer Interaction',
                         'User Experience',
                         'Human-Centered AI',
                         'Eye Tracking',
                         'Cognitive Neuroscience',
                         'Digital Media'],
  'courses': ['02808 Personal Data Interaction for Mobile and Wearables',
              '02809 UX — User Experience and Prototyping'],
  'recent_publications': ['Do not assume that text generated by artificial intelligence is '
                          'interchangeable with human writing — eye-tracking study on AI vs '
                          'human-authored text',
                          'Reading the Reader: Adaptive displays for readers with impaired vision '
                          'using eye tracking',
                          'Eye-tracking based biometric identification using reading patterns'],
  'supervised_topics': ['Eye-tracking biometrics',
                        'Adaptive reading displays',
                        'UX evaluation of AI-generated text',
                        'Font legibility and cognitive load',
                        'Smart reading support using gaze signals'],
  'availability': 'limited',
  'current_students': 4,
  'max_students': 5,
  'building': 'DTU Compute, Building 321',
  'supervisor_summary': 'This researcher works in the Cognitive Systems section at DTU Compute, '
                        'focusing on Human-Computer Interaction, User Experience, Human-Centered '
                        'AI, Eye Tracking, Cognitive Neuroscience, and Digital Media. Active '
                        'research areas include topics such as assume text generated artificial '
                        'intelligence interchangeable. Thesis supervision covers areas such as '
                        'eye-tracking biometrics and adaptive reading displays.'},
 {'name': 'Ashkan Tashk',
  'initials': 'ashta',
  'title': 'Postdoctoral Researcher',
  'section': 'Cognitive Systems',
  'email': 'ashta@dtu.dk',
  'profile_url': 'https://people.compute.dtu.dk/ashta',
  'orbit_url': 'https://orbit.dtu.dk/en/persons/ashkan-tashk',
  'research_interests': ['Eye-Tracking and Pupillometry',
                         'Psychophysics of Reading',
                         'Theory of Visual Attention (TVA)',
                         'Bayesian Modeling',
                         'Human-Centered AI',
                         'Biomedical Signal and Image Processing',
                         'Typography and Font Legibility'],
  'courses': ['02810 UX Design Prototyping (co-teaching)',
              '02266 User Experience Engineering (co-teaching)'],
  'recent_publications': ['MIPLS2: Exploiting PLS2 to Impute Missing Values in a Two-Block System '
                          'with Multiple Response Variables (Analytica Chimica Acta, 2025)',
                          'Artificial Intelligence Application for Metastatic Gastrointestinal '
                          'Cancer: A Systematic Literature Review (Cancers, 2025)',
                          'Epidemiological Description and Trajectories of Patients with Prostate '
                          'Cancer in Denmark (BMC Research Notes, 2024)',
                          'Modelling of Electronic Health Records for Time-Variant Event Learning '
                          '— A Case Study in Prostate Cancer (IEEE Access, 2023)',
                          'AID-U-Net: An Innovative Deep Convolutional Architecture for Semantic '
                          'Segmentation of Biomedical Images (Diagnostics, 2022)'],
  'supervised_topics': ['Adaptive reading interfaces using eye-tracking and cognitive load signals',
                        'Bayesian models for pupillometric cognitive assessment',
                        'Biometric identification through reading patterns using deep learning',
                        'Multimodal cognitive state estimation (eye-tracking + EEG/GSR)',
                        'Font legibility psychophysics experiments',
                        'TEPR analysis for cognitive load measurement'],
  'availability': 'available',
  'current_students': 1,
  'max_students': 3,
  'building': 'DTU Compute, Building 321',
  'supervisor_summary': 'This researcher works in the Cognitive Systems section at DTU Compute, '
                        'focusing on Eye-Tracking and Pupillometry, Psychophysics of Reading, '
                        'Theory of Visual Attention (TVA), Bayesian Modeling, Human-Centered AI, '
                        'Biomedical Signal and Image Processing, and Typography and Font '
                        'Legibility. Active research areas include topics such as mipls2: '
                        'exploiting pls2 impute missing values. Thesis supervision covers areas '
                        'such as adaptive reading interfaces.'},
 {'name': 'Line Katrine Harder Clemmensen',
  'initials': 'lkhc',
  'title': 'Associate Professor',
  'section': 'Cognitive Systems',
  'email': 'lkhc@dtu.dk',
  'profile_url': 'https://people.compute.dtu.dk/lkhc/',
  'orbit_url': 'https://orbit.dtu.dk/en/persons/line-katrine-harder-clemmensen',
  'research_interests': ['AI and Mental Health',
                         'Statistical Learning',
                         'Sparse Methods',
                         'Chemometrics',
                         'Functional Data Analysis'],
  'courses': ['02450 Introduction to Machine Learning and Data Mining',
              '02463 Active Machine Learning and Agency'],
  'recent_publications': ["Penalized classification using Fisher's linear discriminant",
                          'Sparse discriminant analysis for high-dimensional data',
                          'Digital phenotyping for mental health using smartphone data'],
  'supervised_topics': ['Machine learning for mental health diagnostics',
                        'Sparse statistical methods',
                        'Wearable sensor data analysis',
                        'Digital biomarkers'],
  'availability': 'available',
  'current_students': 3,
  'max_students': 6,
  'building': '322',
  'supervisor_summary': 'This researcher works in the Cognitive Systems section at DTU Compute, '
                        'focusing on AI and Mental Health, Statistical Learning, Sparse Methods, '
                        'Chemometrics, and Functional Data Analysis. Active research areas include '
                        "topics such as penalized classification fisher's linear discriminant. "
                        'Thesis supervision covers areas such as machine learning for mental '
                        'health diagnostics and sparse statistical methods.'},
 {'name': 'Anders Bjorholm Dahl',
  'initials': 'abda',
  'title': 'Professor, Head of Section',
  'section': 'Visual Computing',
  'email': 'abda@dtu.dk',
  'profile_url': 'https://people.compute.dtu.dk/abda/',
  'orbit_url': 'https://orbit.dtu.dk/en/persons/anders-bjorholm-dahl',
  'research_interests': ['3D Image Analysis',
                         'AI in Quantitative Analysis',
                         'Computer Vision',
                         'Deep Learning for Microscopy',
                         'Medical Image Analysis'],
  'courses': ['02502 Image Analysis', '02504 Computer Vision'],
  'recent_publications': ['Deep learning for 3D microstructure characterization',
                          'Quantitative analysis of X-ray tomography images',
                          'Automated segmentation of biological tissues'],
  'supervised_topics': ['3D image segmentation with deep learning',
                        'Microstructure analysis from CT scans',
                        'Medical image classification',
                        'Automated quality inspection using computer vision'],
  'availability': 'limited',
  'current_students': 6,
  'max_students': 7,
  'building': '321',
  'supervisor_summary': 'This researcher works in the Visual Computing section at DTU Compute, '
                        'focusing on 3D Image Analysis, AI in Quantitative Analysis, Computer '
                        'Vision, Deep Learning for Microscopy, and Medical Image Analysis. Active '
                        'research areas include topics such as deep learning 3d microstructure '
                        'characterization. Thesis supervision covers areas such as 3d image '
                        'segmentation with deep learning and microstructure analysis from ct '
                        'scans.'},
 {'name': 'Aasa Feragen',
  'initials': 'afhar',
  'title': 'Professor',
  'section': 'Visual Computing',
  'email': 'afhar@dtu.dk',
  'profile_url': 'https://people.compute.dtu.dk/afhar/',
  'orbit_url': 'https://orbit.dtu.dk/en/persons/aasa-feragen',
  'research_interests': ['AI in Medical Image Analysis',
                         'Fairness and Bias in AI',
                         'Geometric Deep Learning',
                         'Shape Analysis',
                         'Statistical Shape Models'],
  'courses': ['02456 Deep Learning', '02505 Advanced Image Analysis'],
  'recent_publications': ['Fairness-aware deep learning for medical imaging',
                          'Riemannian geometry for shape analysis in medical imaging',
                          'Uncertainty quantification in deep learning diagnostics'],
  'supervised_topics': ['Fairness in medical AI',
                        'Geometric deep learning on manifolds',
                        'Uncertainty estimation in image classification',
                        'Bias detection in clinical AI systems'],
  'availability': 'available',
  'current_students': 4,
  'max_students': 7,
  'building': '321',
  'supervisor_summary': 'This researcher works in the Visual Computing section at DTU Compute, '
                        'focusing on AI in Medical Image Analysis, Fairness and Bias in AI, '
                        'Geometric Deep Learning, Shape Analysis, and Statistical Shape Models. '
                        'Active research areas include topics such as fairness-aware deep learning '
                        'medical imaging. Thesis supervision covers areas such as fairness in '
                        'medical ai and geometric deep learning on manifolds.'},
 {'name': 'Siavash Arjomand Bigdeli',
  'initials': 'sarbi',
  'title': 'Tenure-Track Associate Professor',
  'section': 'Visual Computing',
  'email': 'sarbi@dtu.dk',
  'profile_url': 'https://people.compute.dtu.dk/sarbi/',
  'orbit_url': 'https://orbit.dtu.dk/en/persons/siavash-arjomand-bigdeli',
  'research_interests': ['Deep Learning',
                         'Computer Vision',
                         'Generative Models',
                         'Image Restoration',
                         'Diffusion Models'],
  'courses': ['02501 Advanced Deep Learning in Computer Vision'],
  'recent_publications': ['Image restoration using deep generative priors',
                          'Diffusion-based image synthesis and editing',
                          'Score-based models for inverse problems'],
  'supervised_topics': ['Diffusion models for image generation',
                        'Deep image restoration and denoising',
                        'Generative adversarial networks',
                        'Neural image compression'],
  'availability': 'available',
  'current_students': 2,
  'max_students': 5,
  'building': '321',
  'supervisor_summary': 'This researcher works in the Visual Computing section at DTU Compute, '
                        'focusing on Deep Learning, Computer Vision, Generative Models, Image '
                        'Restoration, and Diffusion Models. Active research areas include topics '
                        'such as image restoration deep generative priors. Thesis supervision '
                        'covers areas such as diffusion models for image generation and deep image '
                        'restoration and denoising.'},
 {'name': 'Jeppe Revall Frisvad',
  'initials': 'jerf',
  'title': 'Associate Professor',
  'section': 'Visual Computing',
  'email': 'jerf@dtu.dk',
  'profile_url': 'https://people.compute.dtu.dk/jerf/',
  'orbit_url': 'https://orbit.dtu.dk/en/persons/jeppe-revall-frisvad',
  'research_interests': ['Computer Graphics',
                         'Appearance Modeling',
                         'Rendering',
                         'Optical Properties of Materials',
                         '3D Scanning'],
  'courses': ['02562 Rendering — Introduction to Realistic Image Synthesis',
              '02941 Physically Based Rendering'],
  'recent_publications': ['Multidimensional optical diffusion for measurement of appearance',
                          'Coral-inspired microgeometry for solar energy harvesting',
                          'Efficient Monte Carlo methods for subsurface scattering'],
  'supervised_topics': ['Physically-based rendering techniques',
                        'Material appearance capture and modeling',
                        'Real-time ray tracing',
                        '3D printing appearance reproduction'],
  'availability': 'available',
  'current_students': 2,
  'max_students': 5,
  'building': '321',
  'supervisor_summary': 'This researcher works in the Visual Computing section at DTU Compute, '
                        'focusing on Computer Graphics, Appearance Modeling, Rendering, Optical '
                        'Properties of Materials, and 3D Scanning. Active research areas include '
                        'topics such as multidimensional optical diffusion measurement appearance. '
                        'Thesis supervision covers areas such as physically-based rendering '
                        'techniques and material appearance capture and modeling.'},
 {'name': 'Thomas Bolander',
  'initials': 'tobo',
  'title': 'Professor',
  'section': 'Algorithms, Logic, and Graphs',
  'email': 'tobo@dtu.dk',
  'profile_url': 'https://people.compute.dtu.dk/tobo/',
  'orbit_url': 'https://orbit.dtu.dk/en/persons/thomas-bolander',
  'research_interests': ['Artificial Intelligence',
                         'Social Intelligence',
                         'Multi-Agent Systems',
                         'Modal Logic',
                         'Epistemic Logic',
                         'Automated Planning'],
  'courses': ['02180 Introduction to Artificial Intelligence',
              '02287 Logical Theories for AI Agents'],
  'recent_publications': ['Epistemic planning with implicit coordination',
                          'Theory of mind in multi-agent planning',
                          'Automated reasoning about knowledge and belief'],
  'supervised_topics': ['Multi-agent epistemic planning',
                        'Theory of mind in AI',
                        'Logical foundations of AI',
                        'Social reasoning in robotics'],
  'availability': 'limited',
  'current_students': 5,
  'max_students': 6,
  'building': '322',
  'supervisor_summary': 'This researcher works in the Algorithms, Logic, and Graphs section at DTU '
                        'Compute, focusing on Artificial Intelligence, Social Intelligence, '
                        'Multi-Agent Systems, Modal Logic, Epistemic Logic, and Automated '
                        'Planning. Active research areas include topics such as epistemic planning '
                        'implicit coordination. Thesis supervision covers areas such as '
                        'multi-agent epistemic planning and theory of mind in ai.'},
 {'name': 'Philip Bille',
  'initials': 'phbi',
  'title': 'Professor, Head of Section',
  'section': 'Algorithms, Logic, and Graphs',
  'email': 'phbi@dtu.dk',
  'profile_url': 'https://people.compute.dtu.dk/phbi/',
  'orbit_url': 'https://orbit.dtu.dk/en/persons/philip-bille',
  'research_interests': ['Algorithms',
                         'Data Structures',
                         'String Algorithms',
                         'Data Compression',
                         'Pattern Matching'],
  'courses': ['02105 Algorithms and Data Structures 1', '02110 Algorithms and Data Structures 2'],
  'recent_publications': ['Compressed indexing with signature grammars',
                          'Optimal-time dictionary-compressed indexing',
                          'Fingerprints in compressed strings'],
  'supervised_topics': ['String algorithms and compressed text indexing',
                        'Succinct data structures',
                        'Pattern matching in compressed data',
                        'Algorithm engineering'],
  'availability': 'available',
  'current_students': 3,
  'max_students': 6,
  'building': '322',
  'supervisor_summary': 'This researcher works in the Algorithms, Logic, and Graphs section at DTU '
                        'Compute, focusing on Algorithms, Data Structures, String Algorithms, Data '
                        'Compression, and Pattern Matching. Active research areas include topics '
                        'such as compressed indexing signature grammars. Thesis supervision covers '
                        'areas such as string algorithms and compressed text indexing and succinct '
                        'data structures.'},
 {'name': 'Allan Peter Engsig-Karup',
  'initials': 'apek',
  'title': 'Associate Professor',
  'section': 'Scientific Computing',
  'email': 'apek@dtu.dk',
  'profile_url': 'https://people.compute.dtu.dk/apek/',
  'orbit_url': 'https://orbit.dtu.dk/en/persons/allan-peter-engsig-karup',
  'research_interests': ['High-Performance Computing',
                         'GPU Computing',
                         'Numerical Methods for PDEs',
                         'Wave Simulation',
                         'Quantum Computing'],
  'courses': ['02614 High-Performance Computing', '02623 The Finite Element Method for PDEs'],
  'recent_publications': ['GPU-accelerated spectral element methods for wave problems',
                          'Uncertainty quantification for engineering applications',
                          'Quantum computing for scientific simulation'],
  'supervised_topics': ['GPU-parallel numerical solvers',
                        'Finite element methods for fluid dynamics',
                        'Quantum computing algorithms',
                        'High-performance scientific computing'],
  'availability': 'available',
  'current_students': 3,
  'max_students': 6,
  'building': '324',
  'supervisor_summary': 'This researcher works in the Scientific Computing section at DTU Compute, '
                        'focusing on High-Performance Computing, GPU Computing, Numerical Methods '
                        'for PDEs, Wave Simulation, and Quantum Computing. Active research areas '
                        'include topics such as gpu-accelerated spectral element methods wave '
                        'problems. Thesis supervision covers areas such as gpu-parallel numerical '
                        'solvers and finite element methods for fluid dynamics.'},
 {'name': 'Henrik Madsen',
  'initials': 'hmad',
  'title': 'Professor',
  'section': 'Dynamical Systems',
  'email': 'hmad@dtu.dk',
  'profile_url': 'https://people.compute.dtu.dk/hmad/',
  'orbit_url': 'https://orbit.dtu.dk/en/persons/henrik-madsen',
  'research_interests': ['Stochastic Modelling',
                         'Time Series Analysis',
                         'Energy Systems',
                         'Smart Grids',
                         'Forecasting',
                         'Grey-Box Modelling'],
  'courses': ['02417 Time Series Analysis', '02427 Advanced Time Series Analysis'],
  'recent_publications': ['Grey-box modelling for energy performance of buildings',
                          'Probabilistic forecasting for renewable energy integration',
                          'Stochastic differential equations for smart grid optimization'],
  'supervised_topics': ['Energy forecasting with stochastic models',
                        'Smart building energy optimization',
                        'Wind power prediction',
                        'Grey-box models for physical systems'],
  'availability': 'limited',
  'current_students': 7,
  'max_students': 8,
  'building': '303B',
  'supervisor_summary': 'This researcher works in the Dynamical Systems section at DTU Compute, '
                        'focusing on Stochastic Modelling, Time Series Analysis, Energy Systems, '
                        'Smart Grids, Forecasting, and Grey-Box Modelling. Active research areas '
                        'include topics such as grey-box modelling energy performance buildings. '
                        'Thesis supervision covers areas such as energy forecasting with '
                        'stochastic models and smart building energy optimization.'},
 {'name': 'Lars Kai Hansen',
  'initials': 'lkha',
  'title': 'Professor',
  'section': 'Cognitive Systems',
  'email': 'lkha@dtu.dk',
  'profile_url': 'https://people.compute.dtu.dk/lkha/',
  'orbit_url': 'https://orbit.dtu.dk/en/persons/lars-kai-hansen',
  'research_interests': ['Machine Learning',
                         'Brain-Computer Interfaces',
                         'Neuroinformatics',
                         'Natural Language Processing',
                         'Signal Processing'],
  'courses': ['02460 Advanced Machine Learning', '02462 Signals and Data'],
  'recent_publications': ['EEG-based brain-computer interfaces using deep learning',
                          'Neural topic models for document understanding',
                          'Transfer learning for neuroimaging applications'],
  'supervised_topics': ['Brain-computer interface design',
                        'NLP and topic modeling',
                        'EEG signal analysis with deep learning',
                        'Multimodal learning from brain signals'],
  'availability': 'available',
  'current_students': 3,
  'max_students': 6,
  'building': '321',
  'supervisor_summary': 'This researcher works in the Cognitive Systems section at DTU Compute, '
                        'focusing on Machine Learning, Brain-Computer Interfaces, '
                        'Neuroinformatics, Natural Language Processing, and Signal Processing. '
                        'Active research areas include topics such as eeg-based brain-computer '
                        'interfaces deep learning. Thesis supervision covers areas such as '
                        'brain-computer interface design and nlp and topic modeling.'},
 {'name': 'Jan Madsen',
  'initials': 'jama',
  'title': 'Professor',
  'section': 'Embedded Systems Engineering',
  'email': 'jama@dtu.dk',
  'profile_url': 'https://people.compute.dtu.dk/jama/',
  'orbit_url': 'https://orbit.dtu.dk/en/persons/jan-madsen',
  'research_interests': ['Embedded Systems',
                         'IoT',
                         'TinyML',
                         'Cyber-Physical Systems',
                         'Hardware/Software Co-Design'],
  'courses': ['02155 Computer Architecture and Engineering', '02203 Design of Digital Systems'],
  'recent_publications': ['TinyML for predictive maintenance on edge devices',
                          'Energy-efficient machine learning on microcontrollers',
                          'Holistic review of the TinyML stack'],
  'supervised_topics': ['TinyML deployment on embedded devices',
                        'Edge AI for IoT applications',
                        'Hardware-software co-design for ML',
                        'Low-power intelligent systems'],
  'availability': 'available',
  'current_students': 4,
  'max_students': 7,
  'building': '322',
  'supervisor_summary': 'This researcher works in the Embedded Systems Engineering section at DTU '
                        'Compute, focusing on Embedded Systems, IoT, TinyML, Cyber-Physical '
                        'Systems, and Hardware/Software Co-Design. Active research areas include '
                        'topics such as tinyml predictive maintenance edge devices. Thesis '
                        'supervision covers areas such as tinyml deployment on embedded devices '
                        'and edge ai for iot applications.'},
 {'name': 'Christian Damsgaard Jensen',
  'initials': 'cdje',
  'title': 'Associate Professor',
  'section': 'Cybersecurity Engineering',
  'email': 'cdje@dtu.dk',
  'profile_url': 'https://people.compute.dtu.dk/cdje/',
  'orbit_url': 'https://orbit.dtu.dk/en/persons/christian-damsgaard-jensen',
  'research_interests': ['Computer Security',
                         'Trust Management',
                         'Privacy',
                         'Access Control',
                         'IoT Security'],
  'courses': ['02232 Applied Crypto and Network Security', '02239 Data Security'],
  'recent_publications': ['Trust management in distributed IoT environments',
                          'Privacy-preserving data sharing frameworks',
                          'Reputation-based access control models'],
  'supervised_topics': ['Trust and reputation systems',
                        'Privacy-preserving machine learning',
                        'IoT security architectures',
                        'Blockchain-based access control'],
  'availability': 'available',
  'current_students': 2,
  'max_students': 5,
  'building': '322',
  'supervisor_summary': 'This researcher works in the Cybersecurity Engineering section at DTU '
                        'Compute, focusing on Computer Security, Trust Management, Privacy, Access '
                        'Control, and IoT Security. Active research areas include topics such as '
                        'trust management distributed iot environments. Thesis supervision covers '
                        'areas such as trust and reputation systems and privacy-preserving machine '
                        'learning.'},
 {'name': 'Ekkart Kindler',
  'initials': 'eki',
  'title': 'Associate Professor',
  'section': 'Software Systems Engineering',
  'email': 'eki@dtu.dk',
  'profile_url': 'https://people.compute.dtu.dk/eki/',
  'orbit_url': 'https://orbit.dtu.dk/en/persons/ekkart-kindler',
  'research_interests': ['Model-Driven Software Engineering',
                         'Petri Nets',
                         'Business Process Management',
                         'Formal Methods',
                         'Software Architecture'],
  'courses': ['02161 Software Engineering 1', '02162 Software Engineering 2'],
  'recent_publications': ['Model-driven approaches to process-aware information systems',
                          'Petri net semantics for business process modeling',
                          'Domain-specific languages for adaptive systems'],
  'supervised_topics': ['Model-driven software development',
                        'Business process automation',
                        'Formal verification of software systems',
                        'Domain-specific language design'],
  'availability': 'available',
  'current_students': 2,
  'max_students': 5,
  'building': '322',
  'supervisor_summary': 'This researcher works in the Software Systems Engineering section at DTU '
                        'Compute, focusing on Model-Driven Software Engineering, Petri Nets, '
                        'Business Process Management, Formal Methods, and Software Architecture. '
                        'Active research areas include topics such as model-driven approaches '
                        'process-aware information systems. Thesis supervision covers areas such '
                        'as model-driven software development and business process automation.'},
 {'name': 'Jørgen Villadsen',
  'initials': 'jovi',
  'title': 'Associate Professor',
  'section': 'Algorithms, Logic, and Graphs',
  'email': 'jovi@dtu.dk',
  'profile_url': 'https://people.compute.dtu.dk/jovi/',
  'orbit_url': 'https://orbit.dtu.dk/en/persons/joergen-villadsen',
  'research_interests': ['Automated Reasoning',
                         'Logic Programming',
                         'Formal Verification',
                         'Proof Assistants',
                         'Isabelle/HOL'],
  'courses': ['02156 Logical Systems and Logic Programming', '02256 Automated Reasoning'],
  'recent_publications': ['Formalized soundness and completeness of epistemic logic',
                          'Teaching automated reasoning with Isabelle/HOL',
                          'Formally correct deduction methods for computational logic'],
  'supervised_topics': ['Formal verification using proof assistants',
                        'Logic programming applications',
                        'Automated theorem proving',
                        'Verified functional programming'],
  'availability': 'available',
  'current_students': 2,
  'max_students': 5,
  'building': '322',
  'supervisor_summary': 'This researcher works in the Algorithms, Logic, and Graphs section at DTU '
                        'Compute, focusing on Automated Reasoning, Logic Programming, Formal '
                        'Verification, Proof Assistants, and Isabelle/HOL. Active research areas '
                        'include topics such as formalized soundness completeness epistemic logic. '
                        'Thesis supervision covers areas such as formal verification using proof '
                        'assistants and logic programming applications.'},
 {'name': 'Vagn Lundsgaard Hansen',
  'initials': 'vlha',
  'title': 'Professor Emeritus',
  'section': 'Mathematics',
  'email': 'vlha@dtu.dk',
  'profile_url': 'https://people.compute.dtu.dk/vlha/',
  'orbit_url': 'https://orbit.dtu.dk/en/persons/vagn-lundsgaard-hansen',
  'research_interests': ['Topology',
                         'Differential Geometry',
                         'Mathematics Education',
                         'History of Mathematics'],
  'courses': [],
  'recent_publications': ['Geometry in Nature: exploring the morphology of plants and animals',
                          'Fundamental concepts of topology and differential geometry'],
  'supervised_topics': ['Topological methods in applied mathematics', 'Geometric modeling'],
  'availability': 'unavailable',
  'current_students': 0,
  'max_students': 0,
  'building': '303B',
  'supervisor_summary': 'This researcher works in the Mathematics section at DTU Compute, focusing '
                        'on Topology, Differential Geometry, Mathematics Education, and History of '
                        'Mathematics. Active research areas include topics such as geometry '
                        'nature: exploring morphology plants animals. Thesis supervision covers '
                        'areas such as topological methods in applied mathematics and geometric '
                        'modeling.'},
 {'name': 'Chaudhary Muhammad Aqdus Ilyas',
  'initials': 'cmuai',
  'title': 'Postdoctoral Researcher',
  'section': 'Cognitive Systems',
  'email': 'cmuai@dtu.dk',
  'profile_url': 'https://orbit.dtu.dk/en/persons/chaudhary-muhammad-aqdus-ilyas/',
  'orbit_url': 'https://orbit.dtu.dk/en/persons/chaudhary-muhammad-aqdus-ilyas/',
  'research_interests': ['Affective Computing',
                         'Computer Vision',
                         'Deep Learning',
                         'Human-Robot Interaction',
                         'Eye Tracking',
                         'Adaptive Reading Applications',
                         'Digital Health'],
  'courses': ['02809 UX — User Experience and Prototyping (co-teaching)'],
  'recent_publications': ['Context Preservation Through Eye Tracking: Adaptive Reading Application '
                          'Design for an Optimal Reading Experience',
                          'Do not assume that text generated by artificial intelligence is '
                          'interchangeable with human writing — eye-tracking study',
                          'Computer Vision techniques for Traumatic Brain-Injured People for '
                          'Therapeutic Robot Interaction',
                          'Artificial Emotional Intelligence for Wellbeing — elderly monitoring '
                          'through affective analysis'],
  'supervised_topics': ['Adaptive reading applications with eye tracking',
                        'Context preservation in reading using gaze data',
                        'Affective computing for wellbeing',
                        'Human-robot interaction for therapeutic use',
                        'Computer vision for digital health'],
  'availability': 'available',
  'current_students': 1,
  'max_students': 3,
  'building': 'DTU Compute, Building 321',
  'supervisor_summary': 'This researcher works in the Cognitive Systems section at DTU Compute, '
                        'focusing on Affective Computing, Computer Vision, Deep Learning, '
                        'Human-Robot Interaction, Eye Tracking, Adaptive Reading Applications, and '
                        'Digital Health. Active research areas include topics such as context '
                        'preservation through eye tracking: adaptive. Thesis supervision covers '
                        'areas such as adaptive reading applications with eye tracking and context '
                        'preservation in reading using.'},
 {'name': 'Michael Riis Andersen',
  'initials': 'mria',
  'title': 'Associate Professor',
  'section': 'Cognitive Systems',
  'email': 'mria@dtu.dk',
  'profile_url': 'https://people.compute.dtu.dk/mria/',
  'orbit_url': 'https://orbit.dtu.dk/en/persons/michael-riis-andersen',
  'research_interests': ['Bayesian Machine Learning',
                         'Gaussian Processes',
                         'Probabilistic Modeling',
                         'Approximate Inference',
                         'Neuroscience Applications'],
  'courses': ['02477 Bayesian Machine Learning'],
  'recent_publications': ['Scalable Gaussian process inference with variational methods',
                          'Bayesian optimization for hyperparameter tuning',
                          'Probabilistic models for neural data analysis'],
  'supervised_topics': ['Gaussian process regression and classification',
                        'Variational inference methods',
                        'Bayesian optimization',
                        'Probabilistic modeling for neuroscience'],
  'availability': 'available',
  'current_students': 3,
  'max_students': 5,
  'building': '322',
  'supervisor_summary': 'This researcher works in the Cognitive Systems section at DTU Compute, '
                        'focusing on Bayesian Machine Learning, Gaussian Processes, Probabilistic '
                        'Modeling, Approximate Inference, and Neuroscience Applications. Active '
                        'research areas include topics such as scalable gaussian process inference '
                        'variational methods. Thesis supervision covers areas such as gaussian '
                        'process regression and classification and variational inference methods.'}]


def get_all_advisors():
    """Return full advisor list."""
    return ADVISORS


def get_available_advisors():
    """Return only advisors who are not at capacity."""
    return [
        a for a in ADVISORS
        if a["availability"] != "unavailable"
        and a["current_students"] < a["max_students"]
    ]


def get_sections():
    """Return unique sections."""
    return sorted(set(a["section"] for a in ADVISORS))
